apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod-nginx
spec:
  containers:
    - image: nginx
      name: nginx
      readinessProbe:
        httpGet:
          path: /healthy
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5   