apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello-job
        image: ubuntu
        command:
        - "/bin/bash"
        - "-c"
        - "/bin/echo Hello from pod $(hostname) and date: $(date)"  

---
# failure job
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job-backoff
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello-job
        image: ubuntu
        command:
        - "/bin/bash"
        - "-c"
        - "/bin/ech Hello from pod $(hostname) and date: $(date)"  
