# Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue-green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-app
      color: blue
  template:
    metadata:
      labels:
        app: blue-green-app
        color: blue
    spec:
      containers:
      - name: bluepod
        image: sujanreddy76/nginx:blue
        ports:
        - containerPort: 80  

---
# Green Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: blue-green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-app
      color: green
  template:
    metadata:
      labels:
        app: blue-green-app
        color: green
    spec:
      containers:
      - name: greenpod
        image: sujanreddy76/nginx:green
        ports:
        - containerPort: 80  
---
#  Service for blue-green
apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: blue-green-app
spec:
  type: NodePort
  selector:
    app: blue-green-app
    color: blue
  ports:
  - port: 80 #Service Port
    targetPort: 80  #Container port               
         
