#ClusterIP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterip-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clusterip
  template:
    metadata:
      labels:
        app: clusterip
    spec:
      containers:
        - name: clusterip-container
          image: devopswithcloudhub/nginx:blue
          ports:
            - containerPort: 80
---  
# Service
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP #Default
  selector:
    app: clusterip
  ports:
    - protocol: TCP
      targetPort: 80 # port on the container
      port: 80 # port on the service
