#loadbalancer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
        - name: loadbalancer-container
          image: devopswithcloudhub/nginx:blue
          ports:
            - containerPort: 80
---  
# Service
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer 
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      targetPort: 80 # port on the container
      port: 80 # port on the service
