# Stores data in a specific directory on the k8s node
apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec: 
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo Success!!!! > /output/success.txt']
      volumeMounts: 
        - name: my-host-volume
          mountPath: /output/
  volumes:
  - name: my-host-volume
    hostPath:
      path: /var/data #directory on the host vm

# volumes: volumes will be in the pod spec, these specify the storage volume available to the pods
# volumeMounts(mountPath): volumeMounts will be in the container spec, this reference the volumes in the pod spec.      
