apiVersion: v1
kind: Pod
metadata:
  name: always-pod
spec:
  restartPolicy: Always
  containers:
    - image: busybox
      name: busybox
      command: 
        - "sh"
        - "-c"
        - "sleep 10"  

---
# onFailure
apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod
spec:
  restartPolicy: OnFailure
  containers:
    - image: busybox
      name: busybox
      command: 
        - "sh"
        - "-c"
        - "sleep 10"    
---
# onFailure
apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod-replication
spec:
  restartPolicy: OnFailure
  containers:
    - image: busybox
      name: busybox
      command: 
        - "sh"
        - "-c"
        - "sleep 10 && hahaai"
---
#never
apiVersion: v1
kind: Pod
metadata:
  name: never-pod
spec:
  restartPolicy: Never
  containers:
    - image: busybox
      name: busybox
      command: 
        - "sh"
        - "-c"
        - "sleep 10 && hahaai"  
        

